blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostDetailView,
    PostShareView
)
from .feeds import LatestPostsFeed

from datetime import datetime

from django.contrib.auth import get_user_model
from ninja_extra import api_controller, route, status, NinjaExtraAPI, Router
from ninja_extra.permissions import IsAdminUser, IsAuthenticated
from ninja_jwt.authentication import JWTAuth
from ninja_jwt.tokens import SlidingToken
from .models import Post
from ninja.schema import Schema


class PostSchema(Schema):
    title: str
    slug: str
    body: str
    publish: datetime
    created: datetime
    tags: str


api = Router(auth=JWTAuth())


@api.post('/post', response=PostSchema)
def post_create(request, a: PostSchema):
    a.__dict__.update({'author': request.user, 'status': 'published'})
    Post.objects.create(**a.__dict__)

    data = Post.objects.filter(publish=a.publish).first()
    data.slug = data.id
    data.save()
    for i in a.tags.split(','):
        data.tags.add(i)

    return a.__dict__


class DelPostSchema(Schema):
    pk: int


@api.delete('/post')
def delete_post(request, data: DelPostSchema):
    data = Post.objects.filter(id=data.pk)

    if data.count() != 0:
        data.delete()

    return 'ok'


app_name = 'blog'


urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(),
         name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/share/', PostShareView.as_view(), name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from blog.urls import api as blog_api
from .api import api
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}


api.add_router('/math/', blog_api)

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitempas.views.sitemap'),
    path('markdownx/', include('markdownx.urls')),
    path("api/", api.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/partials/_footer.html
<!-- Footer -->
  <footer class="py-3 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; DjanogBlog {% now "Y" %}</p>
    </div>
    <!-- /.container -->
  </footer>

templates/partials/_latest_posts.html
<!-- Categories Widget -->
<div class="card my-4">
    <h5 class="card-header">Latest Posts</h5>
    <div class="card-body">
        <ul class="list-unstyled mb-0">
            {% for post in latest_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/partials/_navbar.html
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">DjangoBlog</a>
    </div>
</nav>

templates/partials/_search.html
<!-- Search Widget -->
<div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
        <form action="{% url 'blog:post_list' %}" method="get">
            <div class="input-group">
                <input type="search" class="form-control" name="query" placeholder="Search for...">
                <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit">Go!</button>
            </span>
        </div>
        </form>
    </div>
</div>