blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostDetailView,
    PostShareView
)
from .feeds import LatestPostsFeed

from datetime import datetime

from django.contrib.auth import get_user_model
from ninja_extra import api_controller, route, status, NinjaExtraAPI, Router
from ninja_extra.permissions import IsAdminUser, IsAuthenticated
from ninja_jwt.authentication import JWTAuth
from ninja_jwt.tokens import SlidingToken
from .models import Post
from ninja.schema import Schema


class PostSchema(Schema):
    title: str
    slug: str
    body: str
    publish: datetime
    created: datetime
    tags: str


api = Router(auth=JWTAuth())


@api.post('/post', response=PostSchema)
def post_create(request, a: PostSchema):
    a.__dict__.update({'author': request.user, 'status': 'published'})
    Post.objects.create(**a.__dict__)

    data = Post.objects.filter(publish=a.publish).first()
    data.slug = data.id
    data.save()
    for i in a.tags.split(','):
        data.tags.add(i)

    return a.__dict__


class DelPostSchema(Schema):
    pk: int


@api.delete('/post')
def delete_post(request, data: DelPostSchema):
    data = Post.objects.filter(id=data.pk)

    if data.count() != 0:
        data.delete()

    return 'ok'


app_name = 'blog'


urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(),
         name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/share/', PostShareView.as_view(), name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from blog.urls import api as blog_api
from .api import api
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}


api.add_router('/math/', blog_api)

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitempas.views.sitemap'),
    path('markdownx/', include('markdownx.urls')),
    path("api/", api.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = MarkdownxField()
    image = models.ImageField(default='/static/img/defualt.png')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft'
    )

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    def get_content_markdown(self):
        return markdownify(self.body)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.postgres.search import (
    SearchVector, SearchQuery, SearchRank
)
from django.views.generic.edit import FormMixin, FormView
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag

from .models import Post, Comment
from .forms import CommentForm, EmailPostForm


class PostListView(ListView):
    paginate_by = 10
    template_name = 'blog/post-list.html'

    def get_queryset(self, **kwargs):
        queryset = Post.published.all()
        tag_slug = self.kwargs.get('tag_slug')
        query = self.request.GET.get('query')
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            queryset = queryset.filter(tags__in=[tag])
        if query:
            search_vector = SearchVector('title', weight='A') +\
                SearchVector('body', weight='B')
            search_query = SearchQuery(query)

            queryset = Post.published.annotate(
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.kwargs.get('tag_slug')
        context["query"] = self.request.GET.get('query')
        return context


class PostDetailView(FormMixin, DetailView):
    template_name = 'blog/post-detail.html'
    form_class = CommentForm

    def get_object(self):
        obj = get_object_or_404(Post, status='published',
                                slug=self.kwargs.get('slug'),
                                publish__year=self.kwargs.get('year'),
                                publish__month=self.kwargs.get('month'),
                                publish__day=self.kwargs.get('day')
                                )
        return obj

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids)\
            .exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
            .order_by('-same_tags', '-publish')[:4]

        comments = Comment.objects.filter(post=post, active=True)
        context["similar_posts"] = similar_posts
        context['comments'] = comments
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.get_object()
            comment.save()
            return self.form_valid(form)
        else:
            print("Invalid form")
            return self.form_invalid(form)


class PostShareView(FormView):
    form_class = EmailPostForm
    template_name = 'blog/post-share.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = get_object_or_404(
            Post, id=self.kwargs.get('post_id'))
        context["sent"] = False
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        # Send Email
        cd = form.cleaned_data
        post = context['post']
        post_url = self.request.build_absolute_uri(
            post.get_absolute_url()
        )
        subject = f"{cd['name']} recommends you read {post.title}"
        message = f"Read {post.title} at {post_url}\n\n" \
            f"{cd['name']}\'s comments: {cd['comments']}"
        send_mail(subject, message, 'admin@myblog.com', [cd['to']])

        context['sent'] = True
        context['form'] = form
        return self.render_to_response(context)

templates/blog/post-detail.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
 <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ object.title }}</h1>

        <!-- Author -->
        <p class="lead">by {{ object.author }}</p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on {{ object.publish }}</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{ object.image.url }}" alt="">

        <hr>
          {{ object.get_content_markdown | safe }}
        <hr>
        <a href="{% url 'blog:post_share' object.id %}" class="btn btn-info mb-3">Share this post</a>

        <h3 class="bg-primary p-2 text-white mb-3">Similar posts</h3>
        <div class="row">
          {% for post in similar_posts %}
            <div class="col-md-4">
              <div class="card" style="width: 200px">
                <div class="card-image-top">
                  <img src="{{ object.image.url}}" alt="" class="img-fluid">
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                  </h5>
                </div>
              </div>
            </div>
          {% empty %}
            There are no similar posts yet.
          {% endfor %}
        </div>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form action="{{ object.get_absolute_url }}" method="POST">
            
              {% csrf_token %}
              <div class="form-group">
                <label for="name">{{ form.name.label_tag }}</label>
                <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" name="name"
                id="id_name" placeholder="Your name" value="{{ form.name.value|default:""}}">
                {% if form.name.errors %}
                  <div class="invalid-feedback">
                    {{ form.name.errors }}
                  </div>
                {% endif %}
              </div>
              
              <div class="form-group">
                <label for="email">{{ form.email.label_tag }}</label>
                <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" name="email" id="id_email"
                placeholder="Your email" value="{{ form.email.value|default:""}}">
                {% if form.email.errors %}
                  <div class="invalid-feedback">
                    {{ form.email.errors }}
                  </div>
                {% endif %}
              </div>
              <div class="form-group">
                {{form.body.label_tag}}
                <textarea name="body" id="id_body" class="form-control {% if form.body.errors %}is-invalid{% endif %}" rows="3" 
                placeholder="What you wanna tell?">{{ form.body.value|default:""}}</textarea>
                 <div class="invalid-feedback">
                    {{ form.body.errors }}
                  </div>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        {% with comments.count as total_comments %}
          <h3 class="bg-primary p-2 text-white mb-3">
            {{ total_comments }} comment{{ total_comments|pluralize }}
          </h3>
        {% endwith %}

        {% for comment in comments %}
        <!-- Single Comment -->
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0"> Comment {{ forloop.counter }} by <span class="text-secondary">{{ comment.name }}</span> {{ comment.created }}</h5>
             {{ comment.body|linebreaks }}
          </div>
        </div>
        {% endfor %}

      </div>
      
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        {% include 'partials/_search.html' %}

        {% show_latest_posts 5 %}

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Most Commented Post</h5>
          <div class="card-body">
           {% get_most_commented_posts as most_commented_posts %}
            <ul class="list-unstyled">
              {% for post in most_commented_posts %}
                <li>
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
{% endblock content %}

templates/blog/post-list.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
 <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h2 class="my-4">
          Blog Posts
          {% if tag %}<small>Posts tagged with "{{ tag }}"</small>{% endif %}
          {% if query %}<small>Search result for "{{ query }}"</small>{% endif %}
        </h2>

        {% for post in object_list %}
           <!-- Blog Post -->
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-4">
                  <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
                </div>
                <div class="col-8">
                  <h2 class="card-title">{{ post.title }}</h2>
                  <p class="card-text">{{ post.body|truncatewords:"10" }}</p>
                  <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                </div>
              </div>
            </div>
            <div class="card-footer text-muted">
             <div class="d-flex justify-content-between">
              <div>Published {{ post.publish }} by {{ post.author }}</div>
              <div>
                 Tags:
                {% for tag in post.tags.all %}
                  <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                  </a>
                  {% if not forloop.last %}, {% endif %}
                {% endfor %}
              </div>
             </div>
            </div>
          </div>
        {% empty %}
          <p class="lead">No posts found.</p>
        {% endfor %}

       

        {% if is_paginated %}
          {% include 'pagination.html' with page=page_obj %}
        {% endif %}

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        {% include 'partials/_search.html' %}

        {% show_latest_posts 5 %}

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Most Commented Post</h5>
          <div class="card-body">
           {% get_most_commented_posts as most_commented_posts %}
          <ul class="list-unstyled">
            {% for post in most_commented_posts %}
              <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </li>
            {% endfor %}
          </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
{% endblock content %}

templates/blog/post-share.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
 <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8 mt-4">
        <h5 class="card-header">Share "{{ post.title }}" by e-mail</h5>
          {% if sent %}
          <h1>E-mail successfully sent</h1>
          <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
          </p>
        {% else %}
          <div class="card-body">
            <form action="{% url 'blog:post_share' post.id %}" method="POST">
            
              {% csrf_token %}
              <div class="form-group">
                <label for="name">{{ form.name.label_tag }}</label>
                <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" name="name"
                id="id_name" placeholder="Your name" value="{{ form.name.value|default:""}}">
                {% if form.name.errors %}
                  <div class="invalid-feedback">
                    {{ form.name.errors }}
                  </div>
                {% endif %}
              </div>
              
              <div class="form-group">
                <label for="email">{{ form.email.label_tag }}</label>
                <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" name="email" id="id_email"
                placeholder="Your email" value="{{ form.email.value|default:""}}">
                {% if form.email.errors %}
                  <div class="invalid-feedback">
                    {{ form.email.errors }}
                  </div>
                {% endif %}
              </div>
              <div class="form-group">
                <label for="to">{{ form.to.label_tag }}</label>
                <input type="email" class="form-control {% if form.to.errors %}is-invalid{% endif %}" name="to" id="id_to"
                placeholder="Receiver email" value="{{ form.to.value|default:""}}">
                {% if form.to.errors %}
                  <div class="invalid-feedback">
                    {{ form.to.errors }}
                  </div>
                {% endif %}
              </div>
              <div class="form-group">
                {{form.comments.label_tag}}
                <textarea name="comments" id="id_comments" class="form-control" rows="3" 
                placeholder="What you wanna tell?">{{ form.comments.value|default:""}}</textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
          {% endif %}
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        {% include 'partials/_search.html' %}

        {% show_latest_posts 5 %}

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Most Commented Post</h5>
          <div class="card-body">
           {% get_most_commented_posts as most_commented_posts %}
            <ul class="list-unstyled">
              {% for post in most_commented_posts %}
                <li>
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% endblock content %}